# Generated by Django 4.0 on 2021-12-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('flight', models.CharField(max_length=100)),
                ('airline', models.CharField(max_length=100)),
                ('info_url', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('is_departure', models.BooleanField()),
            ],
        ),
    ]
