# Generated by Django 4.0 on 2021-12-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightboard',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
