# Generated by Django 4.0 on 2021-12-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0002_alter_flightboard_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopsInterNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('opening', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contanct_details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopsNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('opening', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contanct_details', models.CharField(max_length=200)),
            ],
        ),
    ]
