# Generated by Django 4.0 on 2021-12-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0004_alter_shopsinternational_contanct_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsnational',
            name='contanct_details',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shopsnational',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shopsnational',
            name='img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shopsnational',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shopsnational',
            name='opening',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shopsnational',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
