# Generated by Django 4.0 on 2022-01-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0008_flightbookdata_bookflighttickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsAndOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flightbookdata',
            name='total_pay',
            field=models.IntegerField(),
        ),
    ]
