# Generated by Django 4.0 on 2022-01-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0009_dealsandoffers_alter_flightbookdata_total_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookflighttickets',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
