# Generated by Django 4.0 on 2022-01-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0010_bookflighttickets_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookflighttickets',
            name='cancel',
        ),
        migrations.AddField(
            model_name='flightbookdata',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
