# Generated by Django 4.0 on 2022-01-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0011_remove_bookflighttickets_cancel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookflighttickets',
            name='flight',
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='destination_place',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='destination_time',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='duration_stop',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='fight_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='flight_image',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='flight_no',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='no_stops',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='origin_place',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='origin_time',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='price',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='refund',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bookflighttickets',
            name='total_pay',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookflighttickets',
            name='cardCvv',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookflighttickets',
            name='cardMonth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookflighttickets',
            name='cardNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookflighttickets',
            name='cardType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookflighttickets',
            name='cardYear',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='FlightBookData',
        ),
    ]
