# Generated by Django 4.0 on 2022-01-05 10:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0013_bookflighttickets_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('Financial', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('Clothes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('Travelaids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('Appliances', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('Health', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('Toiletries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('genral_activity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.bookflighttickets')),
            ],
        ),
    ]
