# Generated by Django 4.0 on 2022-01-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0014_checklistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookflighttickets',
            name='checklistcreated',
            field=models.BooleanField(default=False),
        ),
    ]
