# Generated by Django 4.0 on 2022-01-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0015_bookflighttickets_checklistcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistmodel',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fly.bookflighttickets'),
        ),
    ]
